#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : stestr
Version  : 2.1.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/2a/fd/2a8b894ee3451704cf8525a6a94b87d5ba24747b7bbd3d2f7059189ad79f/stestr-2.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/2a/fd/2a8b894ee3451704cf8525a6a94b87d5ba24747b7bbd3d2f7059189ad79f/stestr-2.1.1.tar.gz
Summary  : A parallel Python test runner built around subunit
Group    : Development/Tools
License  : Apache-2.0
Requires: stestr-bin
Requires: stestr-python3
Requires: stestr-license
Requires: stestr-python
Requires: PyYAML
Requires: cliff
Requires: fixtures
Requires: pbr
Requires: python-future
Requires: python-subunit
Requires: six
Requires: subunit2sql
Requires: testtools
Requires: voluptuous
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : subunit2sql
BuildRequires : tox
BuildRequires : virtualenv
Patch1: deps.patch

%description
==========================

%package bin
Summary: bin components for the stestr package.
Group: Binaries
Requires: stestr-license

%description bin
bin components for the stestr package.


%package license
Summary: license components for the stestr package.
Group: Default

%description license
license components for the stestr package.


%package python
Summary: python components for the stestr package.
Group: Default
Requires: stestr-python3

%description python
python components for the stestr package.


%package python3
Summary: python3 components for the stestr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the stestr package.


%prep
%setup -q -n stestr-2.1.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533852685
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/stestr
cp LICENSE %{buildroot}/usr/share/doc/stestr/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/stestr

%files license
%defattr(-,root,root,-)
/usr/share/doc/stestr/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
