#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : stestr
Version  : 2.3.1
Release  : 5
URL      : https://files.pythonhosted.org/packages/16/ac/0d72ab15807a33c6a762de3dd29741f73ece6032ad2b4c0466dfbe86a3f6/stestr-2.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/16/ac/0d72ab15807a33c6a762de3dd29741f73ece6032ad2b4c0466dfbe86a3f6/stestr-2.3.1.tar.gz
Summary  : A parallel Python test runner built around subunit
Group    : Development/Tools
License  : Apache-2.0
Requires: stestr-bin = %{version}-%{release}
Requires: stestr-license = %{version}-%{release}
Requires: stestr-python = %{version}-%{release}
Requires: stestr-python3 = %{version}-%{release}
Requires: PyYAML
Requires: cliff
Requires: fixtures
Requires: pbr
Requires: python-future
Requires: python-subunit
Requires: six
Requires: subunit2sql
Requires: testtools
Requires: voluptuous
BuildRequires : Sphinx
BuildRequires : Sphinx-python
BuildRequires : buildreq-distutils3
BuildRequires : cliff
BuildRequires : cliff-python
BuildRequires : coverage-python
BuildRequires : ddt
BuildRequires : ddt-python
BuildRequires : doc8-python
BuildRequires : hacking
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-future
BuildRequires : python-mock
BuildRequires : python-mock-python
BuildRequires : restructuredtext_lint-python
BuildRequires : stestr
BuildRequires : subunit2sql
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : voluptuous
BuildRequires : voluptuous-python
Patch1: deps.patch

%description
stestr
======
.. image:: https://img.shields.io/travis/mtreinish/stestr/master.svg?style=flat-square
:target: https://travis-ci.org/mtreinish/stestr
:alt: Build status

%package bin
Summary: bin components for the stestr package.
Group: Binaries
Requires: stestr-license = %{version}-%{release}

%description bin
bin components for the stestr package.


%package license
Summary: license components for the stestr package.
Group: Default

%description license
license components for the stestr package.


%package python
Summary: python components for the stestr package.
Group: Default
Requires: stestr-python3 = %{version}-%{release}

%description python
python components for the stestr package.


%package python3
Summary: python3 components for the stestr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the stestr package.


%prep
%setup -q -n stestr-2.3.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552575424
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/stestr
cp LICENSE %{buildroot}/usr/share/package-licenses/stestr/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/stestr

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/stestr/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
